### ISSUE TITLE
Validation 1 - jwtTokenHandler.ValidateToken throws exception about token lifetime

### ISSUE THREAD

**Issue by techalb** [mohamadlawand087/v8-refreshtokenswithJWT#1]
Hi there, 
great code, we were reviewing it and nice implementation. 
We had just an issue during token verification.
In the first validation (line 204) this method throws an exception:

` var tokenInVerification = jwtTokenHandler.ValidateToken(tokenRequest.Token, _tokenValidationParams, out var validatedToken);`
 
![image](https://user-images.githubusercontent.com/67427666/105858501-b09d8a80-5feb-11eb-96af-b84aed38dbd0.png)

So it shows that token has expired but we can't re-generate it because of jumping directly to exception block.

Obviously we did solve it, but just to let you know if you want to fix it in repo for others in the future.

**Comment by mohamadlawand087** [comment]
Thank you very much for your feedback, I will push a fix shortly. I have updated the catch so it will return a valid message for the user informing them that the token has timeout and they need to re-login. Since we cannot do any verification on the tokens we should not generate a new one.

**Comment by techalb** [comment]
Hi Mohamad,
We think that we can't redirect for re-login because especially for this issue is the RefreshToken. So in our opinion, and in our fix also, we did make some of the validation in the try catch block, within the first if block. In this way you can use tokenRequest from body request to make the proper validation e.g. if storedToken, if storedToken.IsUsed or IsRevoked and finally generateJwt Token.

    private async Task<AuthResult> VerifyAndGenerateToken(TokenRequest tokenRequest)
            {
                var jwtTokenHandler = new JwtSecurityTokenHandler();
    
                try
                {   
                    // Validation 1 - Validation JWT token format
                    var tokenInVerification = jwtTokenHandler.ValidateToken(tokenRequest.Token, _tokenValidationParams, out var validatedToken);
    
                    // Validation 2 - Validate encryption alg
                    if(validatedToken is JwtSecurityToken jwtSecurityToken)
                    {
                        var result = jwtSecurityToken.Header.Alg.Equals(SecurityAlgorithms.HmacSha256, StringComparison.InvariantCultureIgnoreCase);
    
                        if(!result) {
                            return new AuthResult()
                            {
                                Success = false,
                                Errors = new List<string>() {
                                "Invalid token or something went wrong."
                            }
                            };
                        }
                    }
    
                    // Validation 3 - validate expiry date
                    var utcExpiryDate = long.Parse(tokenInVerification.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Exp).Value);
    
                    DateTime expiryDate = UnixTimeStampToDateTime(utcExpiryDate);
    
                    if(expiryDate > DateTime.UtcNow) {
                        return new AuthResult() {
                            Success = false,
                            Errors = new List<string>() {
                                "Token has not yet expired"
                            }
                        };
                    } else {
                        var storedToken = await _apiDbContext.RefreshTokens.FirstOrDefaultAsync(x => x.Token == tokenRequest.RefreshToken);
    
                        if (storedToken == null)
                        {
                            return new AuthResult()
                            {
                                Success = false,
                                Errors = new List<string>() {
                                "Token does not exist"
                            }
                            };
                        }
    
                        // Validation 5 - validate if used
                        if (storedToken.IsUsed)
                        {
                            return new AuthResult()
                            {
                                Success = false,
                                Errors = new List<string>() {
                                "Token has been used"
                            }
                            };
                        }
    
                        // Validation 6 - validate if revoked
                        if (storedToken.IsRevorked)
                        {
                            return new AuthResult()
                            {
                                Success = false,
                                Errors = new List<string>() {
                                "Token has been revoked"
                            }
                            };
                        }
    
                        // update current token 
    
                        storedToken.IsUsed = true;
                        _apiDbContext.RefreshTokens.Update(storedToken);
                        await _apiDbContext.SaveChangesAsync();
    
                        // Generate a new token
                        var dbUser = await _userManager.FindByIdAsync(storedToken.UserId);
                        return await GenerateJwtToken(dbUser);
                    }
    
                    return new AuthResult() {
                        Success = false,
                        Errors = new List<string>()
                        {
                            "Something went wrong."
                        }
                    };
    
                }
                catch(Exception ex)
                {
                    if (ex.Message.Contains("Lifetime validation failed. The token is expired."))
                    {
    
                        // validation 4 - validate existence of the token
                        var storedToken = await _apiDbContext.RefreshTokens.FirstOrDefaultAsync(x => x.Token == tokenRequest.RefreshToken);
    
                        if (storedToken == null)
                        {
                            return new AuthResult()
                            {
                                Success = false,
                                Errors = new List<string>() {
                                "Token does not exist"
                            }
                            };
                        }
    
                        // Validation 5 - validate if used
                        if (storedToken.IsUsed)
                        {
                            return new AuthResult()
                            {
                                Success = false,
                                Errors = new List<string>() {
                                "Token has been used"
                            }
                            };
                        }
    
                        // Validation 6 - validate if revoked
                        if (storedToken.IsRevorked)
                        {
                            return new AuthResult()
                            {
                                Success = false,
                                Errors = new List<string>() {
                                "Token has been revoked"
                            }
                            };
                        }
    
                        // update current token 
    
                        storedToken.IsUsed = true;
                        _apiDbContext.RefreshTokens.Update(storedToken);
                        await _apiDbContext.SaveChangesAsync();
    
                        // Generate a new token
                        var dbUser = await _userManager.FindByIdAsync(storedToken.UserId);
                        return await GenerateJwtToken(dbUser);
    
                    }
                    else
                    {
                        return new AuthResult()
                        {
                            Success = false,
                            Errors = new List<string>() {
                                "Invalid token or something went wrong."
                            }
                        };
                    }
                }
            }
 
Sure you can make your tests and update the code if it seems that problem is solved.

**Comment by mohamadlawand087** [comment]
Thank you for the reply, my advice is not to have a token sent back to the user in case it pass the expiry time. 
- JWT are short lived tokens they should be exist for 5-10 min Max and then get new ones using the refresh tokens
- refresh tokens are long lived tokens they can live for months.
When a refresh token expire it means the user is dormant and not using the app. in this case if someone was able to get the key after the expiry time and generate a token for them a security issue will rise. 

This is why in case the token expired you should prompt the user to login again and not use an old token. 

But everything depends on the use case that you need.

**Comment by techalb** [comment]
Yes understand, but in this case why is used the refresh token? Because if the token has not expired it is caught by the if condition, so you can't refresh it.

So i'm with the first point:

* JWT are short lived tokens they should be exist for 5-10 min Max and then get new ones using the refresh tokens
 
So in my opinionin to make the refresh of token, token should be expired and refreshToken should be valid. 

Anyway that's true, everything depends on the use case. 
Issue closed 😊

**Comment by mohamadlawand087** [comment]
Will close the issue. Thank you for continues feedback.

**Comment by Blacon** [comment]
Hello, I have encountered the same exception. Maybe I am missing something, but what is the point of the Refresh token then? The way the code is right now it will never regenerate the jwt. It will either hit the exception that the jwt is expired or it will exit [at this line](https://github.com/mohamadlawand087/v8-refreshtokenswithJWT/blob/5533a1304f2d13269e1733cd73038805f7b4e8b7/TodoApp/Controllers/AuthManagementController.cs#L221).

**Comment by techalb** [comment]
> Hello, I have encountered the same exception. Maybe I am missing something, but what is the point of the Refresh token then? The way the code is right now it will never regenerate the jwt. It will either hit the exception that the jwt is expired or it will exit [at this line](https://github.com/mohamadlawand087/v8-refreshtokenswithJWT/blob/5533a1304f2d13269e1733cd73038805f7b4e8b7/TodoApp/Controllers/AuthManagementController.cs#L221).

Exactly, this was the reason why I opened this issue, because whatever are the use cases, refresh token is to refresh the short lived access token. In this way as it is currently access token will never be refreshed, but the user have to login every 10 mins 😏

**Comment by mohamadlawand087** [comment]
Refresh tokens are long lived tokens, they should be valid for months not minutes, JWT tokens are short lived tokens, they can live for 10 min. with every regeneration of JWT tokens a new refresh token with a long lived refresh token will be generated

**Comment by Blacon** [comment]
Okay then
We have a jwt that expires in 10 minutes.
We also have a refresh token that expires in 6 months.

What should happen if you try regenerating the jwt after 1 hour? Because right now it fails saying that jwt has expired.
What should happen if you try regenerating the jwt after 5 minutes? Because right now it fails saying that jwt has not expired yet.

**Comment by mohamadlawand087** [comment]
You will need to update the code handle these issue, the provided code is a sample code for you change modify and update. Its not a production ready code. 

Will update the code in the future to handle the current bugs

**Comment by techalb** [comment]
> Refresh tokens are long lived tokens, they should be valid for months not minutes, JWT tokens are short lived tokens, they can live for 10 min. with every regeneration of JWT tokens a new refresh token with a long lived refresh token will be generated

Replace your "JWT tokens" with my "access token" and the sentence will be exactly the same. JWT tokens are also called access token. The problem is currently in which event JWT token is regenerated?

**Comment by techalb** [comment]
> You will need to update the code handle these issue, the provided code is a sample code for you change modify and update. Its not a production ready code.
> 
> Will update the code in the future to handle the current bugs

Ok this is an acceptable answer 😁

**Comment by Blacon** [comment]
Side not. I think I found a problem with datetime conversions [in this method](https://github.com/mohamadlawand087/v8-refreshtokenswithJWT/blob/5533a1304f2d13269e1733cd73038805f7b4e8b7/TodoApp/Controllers/AuthManagementController.cs#L310) the datetime is converted to local time, but then [later ](https://github.com/mohamadlawand087/v8-refreshtokenswithJWT/blob/5533a1304f2d13269e1733cd73038805f7b4e8b7/TodoApp/Controllers/AuthManagementController.cs#L221) it is checked against utc time. Which might cause some issues.
